# Generated by Django 2.1.7 on 2019-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='feature',
            field=models.CharField(max_length=16, verbose_name='权限名'),
        ),
    ]
